// SQuBOK用語集データ (#8)
const GLOSSARY = [
  { term: 'SQuBOK', reading: 'えすきゅーぼっく', chapter: 1, desc: 'Software Quality Body of Knowledge の略。ソフトウェア品質の知識体系をまとめたガイド。' },
  { term: '品質', reading: 'ひんしつ', chapter: 1, desc: '本来備わっている特性の集まりが要求事項を満たす程度。ISO 9000で定義。' },
  { term: '品質マネジメント', reading: 'ひんしつまねじめんと', chapter: 2, desc: '品質に関して組織を指揮し管理するための調整された活動。品質計画、品質保証、品質管理、品質改善を含む。' },
  { term: 'QMS', reading: 'きゅーえむえす', chapter: 2, desc: 'Quality Management System（品質マネジメントシステム）。ISO 9001で規定される品質を管理するための仕組み。' },
  { term: 'PDCA', reading: 'ぴーでぃーしーえー', chapter: 2, desc: 'Plan-Do-Check-Act の改善サイクル。品質マネジメントの基本的な考え方。' },
  { term: 'V字モデル', reading: 'ぶいじもでる', chapter: 3, desc: '開発工程とテスト工程を対応させたモデル。要件定義↔受入テスト、基本設計↔結合テストなど。' },
  { term: 'レビュー', reading: 'れびゅー', chapter: 3, desc: '成果物を検証するための静的テスト技法。インスペクション、ウォークスルー等がある。' },
  { term: 'インスペクション', reading: 'いんすぺくしょん', chapter: 3, desc: 'モデレータが主導する最も形式的なレビュー手法。欠陥の検出と記録を体系的に行う。' },
  { term: 'ウォークスルー', reading: 'うぉーくするー', chapter: 3, desc: '作成者が主導するレビュー手法。成果物の内容を参加者に説明しながら確認する。' },
  { term: '同値分割', reading: 'どうちぶんかつ', chapter: 3, desc: '入力値を同値クラスに分け、各クラスから代表値を選んでテストする技法。' },
  { term: '境界値分析', reading: 'きょうかいちぶんせき', chapter: 3, desc: '同値クラスの境界付近の値でテストする技法。バグは境界に集中しやすい。' },
  { term: 'デシジョンテーブル', reading: 'でしじょんてーぶる', chapter: 3, desc: '条件の組み合わせとそれに対するアクションを表形式で整理するテスト設計技法。' },
  { term: '状態遷移テスト', reading: 'じょうたいせんいてすと', chapter: 3, desc: 'システムの状態と遷移をモデル化し、状態遷移図・表に基づいてテストケースを導出する技法。' },
  { term: 'カバレッジ', reading: 'かばれっじ', chapter: 3, desc: 'テストの網羅性を示す指標。命令カバレッジ、分岐カバレッジ、条件カバレッジ等がある。' },
  { term: 'MC/DC', reading: 'えむしーでぃーしー', chapter: 3, desc: 'Modified Condition/Decision Coverage。各条件が独立して判定結果に影響することを確認するカバレッジ基準。' },
  { term: 'ミューテーションテスト', reading: 'みゅーてーしょんてすと', chapter: 3, desc: 'プログラムに意図的な変異（バグ）を埋め込み、テストスイートの欠陥検出能力を評価する手法。' },
  { term: 'FMEA', reading: 'えふえむいーえー', chapter: 4, desc: 'Failure Mode and Effects Analysis（故障モード影響分析）。潜在的な故障モードとその影響を分析する手法。' },
  { term: 'FTA', reading: 'えふてぃーえー', chapter: 4, desc: 'Fault Tree Analysis（故障の木解析）。トップ事象から原因をトップダウンで分析する手法。' },
  { term: 'セキュリティテスト', reading: 'せきゅりてぃてすと', chapter: 4, desc: '情報セキュリティの脆弱性を検出するためのテスト。ペネトレーションテスト等を含む。' },
  { term: 'ユーザビリティ', reading: 'ゆーざびりてぃ', chapter: 4, desc: '特定の利用状況において、特定のユーザが特定の目標を達成する際の有効性・効率性・満足度。ISO 9241-11。' },
  { term: 'アクセシビリティ', reading: 'あくせしびりてぃ', chapter: 4, desc: '年齢や障害の有無に関わらず、すべての人が製品やサービスを利用できること。WCAG等の基準がある。' },
  { term: 'ISO 9001', reading: 'あいえすおー9001', chapter: 2, desc: '品質マネジメントシステムの国際規格。顧客満足の向上と継続的改善を目指す。' },
  { term: 'ISO 25010', reading: 'あいえすおー25010', chapter: 1, desc: 'ソフトウェア製品の品質モデルを定義。機能適合性、性能効率性、互換性、使用性、信頼性、セキュリティ、保守性、移植性の8特性。' },
  { term: 'CMMI', reading: 'しーえむえむあい', chapter: 2, desc: 'Capability Maturity Model Integration。組織のプロセス成熟度を5段階で評価するモデル。' },
  { term: 'アジャイル', reading: 'あじゃいる', chapter: 5, desc: '変化に迅速に対応する反復的・漸進的な開発手法の総称。スクラム、XP等が含まれる。' },
  { term: 'DevOps', reading: 'でぶおぷす', chapter: 5, desc: '開発（Dev）と運用（Ops）を統合し、継続的インテグレーション/デリバリーを実現する文化・プラクティス。' },
  { term: 'CI/CD', reading: 'しーあいしーでぃー', chapter: 5, desc: 'Continuous Integration / Continuous Delivery。コードの統合・テスト・デプロイを自動化するプラクティス。' },
  { term: 'テスト駆動開発', reading: 'てすとくどうかいはつ', chapter: 5, desc: 'TDD (Test Driven Development)。テストを先に書き、テストが通るようにコードを書く開発手法。' },
  { term: '信頼性', reading: 'しんらいせい', chapter: 1, desc: '指定された条件下で、指定された期間、意図した機能を果たす能力。ISO 25010の品質特性の一つ。' },
  { term: '保守性', reading: 'ほしゅせい', chapter: 1, desc: 'ソフトウェアが修正される際の容易さ。モジュール性、再利用性、解析性、修正性、試験性を含む。' },
];
